/* Generated By:JavaCC: Do not edit this line. TheParserConstants.java */
package persistentPG;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TheParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 46;
  /** RegularExpression Id. */
  int DOUBLE = 47;
  /** RegularExpression Id. */
  int EXPON = 48;
  /** RegularExpression Id. */
  int TRUE = 56;
  /** RegularExpression Id. */
  int FALSE = 57;
  /** RegularExpression Id. */
  int CHAR = 58;
  /** RegularExpression Id. */
  int STRING = 59;
  /** RegularExpression Id. */
  int TEXT = 60;
  /** RegularExpression Id. */
  int IDENT = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"refutationEvent[\"",
    "\"]\"",
    "\"persistentClaim[\"",
    "\".\"",
    "\"from\"",
    "\"Alice\"",
    "\"Bob\"",
    "\"instance\"",
    "\"solution\"",
    "\"of\"",
    "\"propose\"",
    "\"oppose\"",
    "\"protocolRequest\"",
    "\"provide\"",
    "\"solve\"",
    "\"protocolResponse\"",
    "\"agree\"",
    "\"strengthening\"",
    "\"refuting\"",
    "\"scg_config[\"",
    "\"domain:\"",
    "\"protocols:\"",
    "\"tournamentStyle:\"",
    "\"turnDuration:\"",
    "\"maxNumAvatars:\"",
    "\"minStrengthening:\"",
    "\"initialReputation:\"",
    "\"maxReputation:\"",
    "\"reputationFactor:\"",
    "\"minProposals:\"",
    "\"maxProposals:\"",
    "\"numRounds:\"",
    "\"proposedClaimMustBeNew:\"",
    "\"minConfidence:\"",
    "\"isPersistentPlayground:\"",
    "\"numOfTournamentRounds:\"",
    "\"full\"",
    "\"round-robin\"",
    "\"knockout\"",
    "\"swiss\"",
    "\"red\"",
    "\"black\"",
    "\"playerspec[\"",
    "\"passwd[\"",
    "\"team[\"",
    "<INT>",
    "<DOUBLE>",
    "<EXPON>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 54>",
    "<token of kind 55>",
    "\"true\"",
    "\"false\"",
    "<CHAR>",
    "<STRING>",
    "<TEXT>",
    "<IDENT>",
  };

}
